### 生成 MCU 测试图片数据的脚本
### 这个脚本会生成一个 C 语言头文件，里面包含一张指定大小的图片数据
### 你可以选择用一张真实图片，或者生成固定数值/随机数据
### 生成的头文件可以直接包含到你的 MCU 项目中，用于测试

import numpy as np
from PIL import Image
import sys
import os
import argparse

# --- 配置 ---
TARGET_WIDTH = 96
TARGET_HEIGHT = 96
CHANNELS = 3

parser = argparse.ArgumentParser(
    description='Generate MCU test image data header file.'
)
parser.add_argument(
    '--mode',
    type=str,
    default='image',
    choices=['image', 'fixed'],
    help="Mode: 'image' (real image) or 'fixed' (fixed value/random)",
)
parser.add_argument(
    '--image_path',
    type=str,
    default='airplane.jpg',
    help="Path to input image (if mode is 'image')",
)
parser.add_argument(
    '--fixed_value',
    type=str,
    default='1',
    help="Fixed value (0-255) or 'random' (if mode is 'fixed')",
)

args = parser.parse_args()

MODE = args.mode
IMAGE_PATH = args.image_path

# Handle fixed_value parsing
if args.fixed_value == 'random':
    FIXED_VALUE = 'random'
else:
    try:
        FIXED_VALUE = int(args.fixed_value)
    except ValueError:
        print(f"Warning: Invalid fixed_value '{args.fixed_value}', defaulting to 0")
        FIXED_VALUE = 0


def generate_header(data, array_name="image_data"):
    """生成 C 语言头文件格式的字符串"""
    flattened = data.flatten()
    hex_data = [f"0x{x:02x}" for x in flattened]

    c_code = f"// Generated by Python script\n"
    c_code += f"// Shape: {TARGET_HEIGHT}x{TARGET_WIDTH}x{CHANNELS}\n"
    c_code += f"// Size: {len(hex_data)} bytes\n\n"
    c_code += f"#include <stdint.h>\n\n"
    c_code += f"const uint8_t {array_name}[] = {{\n"

    # 每行打印 12 个字节，保持美观
    for i in range(0, len(hex_data), 12):
        chunk = hex_data[i : i + 12]
        c_code += "    " + ", ".join(chunk) + ",\n"

    c_code += "};\n"
    return c_code


def main():
    print(f"正在生成 {TARGET_WIDTH}x{TARGET_HEIGHT}x{CHANNELS} 的测试数据...")

    # 创建一个假图片以免脚本报错
    print("生成一张彩虹测试图...")
    data = np.zeros((TARGET_HEIGHT, TARGET_WIDTH, CHANNELS), dtype=np.uint8)

    if MODE == 'image':
        if not os.path.exists(IMAGE_PATH):
            print(f"错误: 找不到图片 {IMAGE_PATH}")

            for y in range(TARGET_HEIGHT):
                for x in range(TARGET_WIDTH):
                    data[y, x, 0] = x * 255 // TARGET_WIDTH  # R
                    data[y, x, 1] = y * 255 // TARGET_HEIGHT  # G
                    data[y, x, 2] = 128  # B
        else:
            print(f"读取图片: {IMAGE_PATH}")
            img = Image.open(IMAGE_PATH).convert('RGB')
            img = img.resize((TARGET_WIDTH, TARGET_HEIGHT))
            data = np.array(img, dtype=np.uint8)

    elif MODE == 'fixed':
        if FIXED_VALUE == 'random':
            print("生成固定种子(Seed=42)的随机数据...")
            np.random.seed(42)
            data = np.random.randint(
                0, 255, (TARGET_HEIGHT, TARGET_WIDTH, CHANNELS), dtype=np.uint8
            )
        else:
            print(f"生成全 {FIXED_VALUE} 的数据...")
            data = np.full(
                (TARGET_HEIGHT, TARGET_WIDTH, CHANNELS), FIXED_VALUE, dtype=np.uint8
            )

    # 验证形状
    assert data.shape == (TARGET_HEIGHT, TARGET_WIDTH, CHANNELS)

    # 生成代码
    c_source = generate_header(data)

    # 写入文件
    output_filename = "image_data.h"
    with open(output_filename, "w") as f:
        f.write(c_source)

    print(f"成功！数据已保存到 {output_filename}")
    print("请将该文件内容复制到你的 MCU 项目中 (通常是 image_load.c 或 main.c 附近)。")


if __name__ == "__main__":
    main()
